version: '3.8'

services:
  vk-news-parser:
    build: .
    image: vk-news-parser:latest
    container_name: vk-news-parser
    #env_file:
    #  - .env
    volumes:
      - ./config:/usr/src/app/config
    restart: unless-stopped